# Offense count: 3
Lint/MissingSuper:
  Exclude:
    - "app/graphql/sources/batched_active_records.rb"
    - "app/graphql/sources/batched_associations_by_foreign_key.rb"
    - "app/graphql/sources/batched_associations_by_many_to_many.rb"

# Offense count: 7
# Configuration parameters: AllowedMethods, AllowedPatterns, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 45

# Offense count: 3
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
# AllowedMethods: refine
Metrics/BlockLength:
  Max: 99

# Offense count: 2
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 9

# Offense count: 6
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 19

# Offense count: 2
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 9

# Offense count: 1
Naming/ConstantName:
  Exclude:
    - "lib/tasks/import_json_data.rake"

# Offense count: 1
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: as, at, by, cc, db, id, if, in, io, ip, of, on, os, pp, to
Naming/MethodParameterName:
  Exclude:
    - "app/controllers/graphql_controller.rb"

# Offense count: 45
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Enabled: false
