require:
  - rubocop-performance
  - rubocop-rubycw

AllCops:
  DisabledByDefault: true
  Exclude:
    - "gems/**/*"
  NewCops: enable
  AllCops:
    SuggestExtensions: false

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Lint:
  Enabled: true

Performance:
  Enabled: true

Rubycw:
  Enabled: true

Security:
  Enabled: true
