source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.0'
gem 'bootsnap', require: false
gem 'faraday-http-cache'
gem 'google-cloud-firestore'
gem 'graphiql-rails'
gem 'graphql'
gem 'jwt'
gem 'pg'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'rails', '~> 7.0.4', '>= 7.0.4.3'
gem 'sass-rails'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development do
  gem 'rubocop', '~> 1.50'
  gem "rubocop-performance", "~> 1.17"
  gem "rubocop-rubycw", "~> 0.1.6"
end

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'katakata_irb'
end
