source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.0'
gem 'bootsnap', require: false
gem 'pg'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.4', '>= 7.0.4.3'
gem 'tzinfo-data', platforms: %i[ mingw mswin x64_mingw jruby ]
# gem 'rack-cors'
gem 'google-cloud-firestore'
gem 'graphql'

group :development do
  gem 'graphiql-rails'
  gem 'sass-rails'
end

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
end
