import { GameList } from "@/components/GameList";
import { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>clip-games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-8 my-4">
        <GameList />
      </div>
    </div>
  );
};

export const getServerSideProps = async () => {
  return {};
};

export default Home;
