import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import { useGames } from "./hooks/game";

const Home: NextPage = () => {
  const games = useGames();

  return (
    <div className="py-0 px-8">
      <Head>
        <title>clip-games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-16 px-0 flex flex-1 flex-col justify-center items-center">
        <h1 className="text-5xl font-mono text-center mb-5">
          Welcome to{" "}
          <a
            href="google.com"
            className="text-teal-500 no-underline hover:underline"
          >
            clip-games
          </a>
        </h1>
        <div className="grid grid-cols-3">
          {games.map((game) => {
            return (
              <div key={game.id} className="relative">
                <Image
                  width="100%"
                  height="320px"
                  layout="responsive"
                  objectFit="contain"
                  src={
                    game.imageUrl ??
                    "https://placehold.jp/eeeeee/cccccc/200x400.png?text=No%20Image"
                  }
                  alt="game image"
                />

                <div> {game.title}</div>
                <div> {game.publisher}</div>
                <div>
                  {game.clipCount} | {game.ratingCount}
                </div>
              </div>
            );
          })}
        </div>
      </main>

      <footer className="flex justify-center items-center flex-grow">
        Powered by{"   "}
        <span>
          <a
            href="https://twitter.com/canisterism"
            target={`_blank`}
            className="ml-2 text-blue-300 no-underline hover:underline"
          >
            canisterism
          </a>
        </span>
      </footer>
    </div>
  );
};

export default Home;
