import { createApolloClient } from "@/graphql/client";
import { GameDocument, GameQuery } from "@/graphql/generated/graphql";
import { GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";

type PageProps = {
  game: GameQuery["game"];
};

export function Game(props: PageProps) {
  return (
    <div>
      <Head>
        <title>{props.game.id} | clip-games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-8 my-4">
        <div className="flex flex-column gap-5">
          <div className="relative h-96 w-64">
            <Image
              src={props.game.imageUrl || ""}
              alt={props.game.title}
              objectFit="contain"
              layout="fill"
            />
          </div>
          <div className="text-white flex">
            <p>{props.game.id}</p>
            <p>{props.game.title}</p>
            <p>{props.game.reviewsCount}</p>
            <p>{props.game.publishedAt}</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const token = context.req.cookies["auth"];
  const client = createApolloClient(token);

  const { id } = context.query;
  if (typeof id !== "string") {
    return {
      notFound: true,
    };
  }

  const { data } = await client.query({
    query: GameDocument,
    variables: {
      gameId: id,
    },
  });
  console.log({ data });
  const game = data.game;
  return { props: { game } };
};

export default Game;
