name: Deploy to Cloud Run

on:
  push:
    branches:
      - master
      - cloudrun # TODO:後で消す

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.14

      - name: Login to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_PRD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          tags: asia-northeast1-docker.pkg.dev/clip-games/cloud-run-source/application:latest
          push: true

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: clip-games
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_PRD }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy applicaiton \
            --image asia-northeast1-docker.pkg.dev/clip-games/cloud-run-source/application:latest \
            --platform managed \
            --region asia-northeast1 \
            --allow-unauthenticated \
            --set-env-vars RAILS_MASTER_KEY=$(gcloud secrets versions access latest --secret="production-key") \
            --set-env-vars RAILS_ENV=production
